### ISSUE TITLE
Support building Telegram X on Windows platform

### ISSUE THREAD

**Issue by vkryl** [TGX-Android/Telegram-X#137]
Currently building Telegram X requires macOS or Linux-based operating system. Once building on Windows platform will be officially supported, the requirement in README could be modified.

**Comment by AlexandrKozlovskiy** [comment]
@vkryl Why do you use shell scripts. May be it better use,for example,python scripts,so it will works for windows and more people know python language,than shell language. I have windows,and i want to build telegram x. I am android developer,so i have all necessary components. @vkryl can you please describe in readme,what to do shell scripts,to windows users can do it itself,because not all users have time to learn shell language,and in my opinion it possible to build telegram x for windows,if we do manually all,what to do shell scripts. For example i modified myself file local.properties and fill all values. I dont know,whether it windows build issue,or common issue,so i not create separate issue,but during of building on the windows i have an error:

Failed to calculate the value of property 'namespace'.
Package Name not found in C:\Users\ksash\tgx\app\src\main\AndroidManifest.xml, and namespace not specified. Please specify a namespace for the generated R and BuildConfig classes via android.namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}


In manifest you haven't package name. In local.properties i fill all values. I not modified librarys,as it do shell scripts,but it seems,this issue not connected with it,because i even not started to build app. My file local.properties is:

```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
# Path to Android SDK
sdk.dir=C\:\\Users\\ksash\\AppData\\Local\\Android\\Sdk

## Path to the keystore file
keystore.file=c:/my_release.keystore

## Package name
app.id=org.thunderdog.challegram

## Project name
app.name=Telegram x

## Link to the app's website. If unavailable, link to the market page could be used.
app.download_url=https://example.com/android

## Obtain credentials to access Telegram API:
# https://core.telegram.org/api/obtaining_api_id
telegram.api_id=my_id
telegram.api_hash=my_hash

# YouTube API key
youtube.api_key=my_key
```

**Comment by vkryl** [comment]
@AlexandrKozlovskiy it is much more than just updating `local.properties` file, as these scripts are also building some native dependencies, and it is not possible to properly support building on Windows without understanding every detail of these scripts. In the meantime it is recommended to install any Linux distributive (e.g. Ubuntu) on a virtual machine, until someone would be able to close the issue.

**Comment by AlexandrKozlovskiy** [comment]
@vkryl I know,what it not only local.properties file. But i have error during gradle sync,as i wrote. I think,if you in readme describe very detail,what we should do,to build telegram without shell scripts,you can close this issue,because even people,which dont know shell can simple repeat all steps on any OS. As i see,this scripts,for example,install android-sdk and copy some folders on other place. Also this scripts do some replacements. Any of this things we can do manually,so in my opinion it will be enough describe in readme,what we should do manually,to build telegram x. After this,in my opinion,you can close this issue.

**Comment by sharunkumar** [comment]
Anyone got to building this on WSL? Would like to know if there's any hurdles to keep an eye out for

**Comment by gmy77** [comment]
I wait the day... if arrive... to find TelegramX for Windows "directly" builded... Fantastic day.
