### ISSUE TITLE
🏆 Telegram X Android Competition: Round 2. Improved Search

### ISSUE THREAD

**Issue by vkryl** [TGX-Android/Telegram-X#237]
**Task description and mockups**: https://contest.com/docs/TgX-Oct22-Round2#3-improved-search
**Deadline**: 23:59 on October 30th (Dubai time).
**Bounty**: $4,000
**Terms**: https://t.me/contest/300

Reference this issue when submitting a pull request that implements this task.

**Comment by vkryl** [comment]
All APKs of the PRs submitted addressing this task can be found here: https://t.me/tgx_prs/316

**Comment by Whitebrim** [comment]
Message selection is not working in search mode ([0b81a35](https://github.com/TGX-Android/Telegram-X/pull/246/commits/0b81a35f1791ecb8c6abe0e5fed6032c207fa3f7)).
Is it intentional? I use search for forwarding multiple messages and I'm tired of exiting search mode to select messages.
Can you please exit search mode automatically and enter message selecting mode if user tap and hold message?

Sorry if this feedback is late or not in the proper thread~
