### ISSUE TITLE
removed all of my life!!!

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [TGX-Android/Telegram-X#442]
Hello
The chat between me and my wife was suddenly deleted this evening. All our photos and content and all our text chats were deleted. This happened on two devices at the same time. This chat is 3 years old and contains our important information and photos, such as engagement, wedding; It is our life and work. Please return our chat to us because our life is only saved in telegram chat. We trust telegram to save our lives. and now i have some data in my telegam but not online , it was download and when i onlin agin it will removing because in telegram web i dont have any thing. how can i backup my last offline data in my android telegram x or back my lost data ????

**Comment by vkryl** [comment]
When chat disappears for both participants, this means it was deleted for both sides by one of the participants (you or your wife in this case, or potentially any third-party who had physical access to the device). This is the way Telegram platform works, and it doesn't matter which specific official Telegram client was used.

The only chance to recover any part of the content of that chat is to have Telegram session, which was offline since before chat was deleted, and you have that chat cached & media downloaded. The moment you turn on network on such device, the offline cache on such device will be deleted.

This can be applied to any Telegram client, which has offline chats cache (which includes Telegram X).

**Comment by MohammadtaghiFarkhondekar** [comment]
@vkryl 

How can I exporting my cache chat data from telegram app or telegram database ( in Android or IOS ) ??
my chat has 1B text and 10,000 photo
My cache data still available because I'm working with offline phone

**Comment by GhGym** [comment]
Did you solve it @MohammadtaghiFarkhondekar ? I'm facing the same issue

**Comment by earmin** [comment]
Hi @MohammadtaghiFarkhondekar, were you able to find a solution for that? I also read your post on XDA and is having the same issue for a friend. It's so crucial for him to be able to extract the chat histories from his non-root offline old Samsung.
